<script>
  import ProjectCard from '$lib/home/ProjectCard.svelte';
  import SkillCard from '$lib/home/Skill/Card.svelte';
  import SkillSection from '$lib/home/Skill/Section.svelte';
</script>

<svelte:head>
  <title>Home | Keyvan Atashfaraz</title>
  <meta
    name="keywords"
    content="Keyvan, Keyvan Atashfaraz, Atashfaraz, Software Engineer, Software Developer, Developer, Engineer, Programmer, Java, Go, Bash, TerraForm, Kubernetes, HTML, CSS, SCSS, LESS, JavaScript, TypeScript, PHP, Python, Haskell, C, C++, Markdown, Hugo, Svelte, SvelteKit, Docs, Personal Website, Personal, hContainers" />
  <meta name="author" content="Keyvan Atashfaraz" />
  <meta name="description" content="Keyvan's personal website" />
</svelte:head>

<section>
  <h1>Hi, I'm <span class="name">Keyvan</span></h1>
  I'm a Software Engineer.
</section>
<section>
  <h1>Skills</h1>
  <SkillSection name="Infrastructure">
    <SkillCard name="TerraForm" level="10" />
    <SkillCard name="Kubernetes" level="9" />
  </SkillSection>
  <SkillSection name="Programming Languages">
    <SkillCard name="Java" level="10" />
    <SkillCard name="Bash" level="9" />
    <SkillCard name="Go" level="7" />
    <SkillCard name="JavaScript" level="8" />
    <SkillCard name="TypeScript" level="7" />
    <SkillCard name="PHP" level="5" />
    <SkillCard name="CSS/SCSS/LESS" level="8" />
    <SkillCard name="Python" level="6" />
    <SkillCard name="Haskell" level="5" />
    <SkillCard name="C/C++" level="4" />
  </SkillSection>
  <SkillSection name="Markup Languages">
    <SkillCard name="HTML" level="10" />
    <SkillCard name="Markdown" level="10" />
  </SkillSection>
  <SkillSection name="Frameworks" />
</section>
<section>
  <h1>Projects</h1>
  <div>
    <ProjectCard
      name="Personal Website"
      description="This is my personal website. It is a static site which is generated by sveltekit."
      repo="https://github.com/k3y0708/personal" />
    <ProjectCard
      name="Docs"
      description="Docs is a documentation about various dev topics. It is a static site which is generated by hugo."
      repo="https://github.com/k3y0708/docs" />
    <ProjectCard
      name="hContainers"
      description="hContainers is a CLI tool for creating vms which runs containers in the Hetzner Cloud. The vms are created and managed by the hContainers CLI so the user can focus creating the software which runs in the containers which are also managed by the hContainers CLI."
      repo="https://github.com/hContainers/hContainers" />
    <ProjectCard
      name="hContainersRouter"
      description="This is a router for a runner from hContainers. It (should) support a routing based on the address when using the IP address of the vm and a routing based on the domain name when assigning a (sub)domain to the vm."
      repo="https://github.com/hContainers/hContainersRouter" />
    <ProjectCard
      name="Crayon"
      description="Crayon is a go library for creating colored output in the terminal."
      repo="https://github.com/hContainers/crayon" />
  </div>
</section>

<style>
  div {
    display: flex;
    flex-wrap: wrap;
  }
</style>
