<script>
  import ProjectCard from '$lib/home/ProjectCard.svelte';
  import SkillCard from '$lib/home/Skill/Card.svelte';
  import SkillSection from '$lib/home/Skill/Section.svelte';
</script>

<svelte:head>
  <title>Home | Keyvan Atashfaraz</title>
  <meta
    name="keywords"
    content="Keyvan, Keyvan Atashfaraz, Atashfaraz, Software Engineer, Software Developer, Developer, Engineer, Programmer, Java, Go, Bash, TerraForm, Kubernetes, HTML, CSS, SCSS, LESS, JavaScript, TypeScript, PHP, Python, Haskell, C, C++, Markdown, Hugo, Svelte, SvelteKit, Docs, Personal Website, Personal, hContainers" />
  <meta name="author" content="Keyvan Atashfaraz" />
  <meta name="description" content="Keyvan's personal website" />
</svelte:head>

<section>
  <h1>Hi, I'm <span class="name">Keyvan</span></h1>
  <span>I'm a Software Engineer.</span>
</section>
<section>
  <h1>Projects</h1>
  <div>
    <ProjectCard
      name="Personal Website"
      description="This is my personal website. It is a static site which is generated by sveltekit."
      repo="https://github.com/k3y0708/personal" />
    <ProjectCard
      name="Docs"
      description="Docs is a documentation about various dev topics. It is a static site which is generated by hugo."
      repo="https://github.com/k3y0708/docs" />
    <ProjectCard
      name="hContainers"
      description="hContainers is a CLI tool for creating vms which runs containers in the Hetzner Cloud. The vms are created and managed by the hContainers CLI so the user can focus creating the software which runs in the containers which are also managed by the hContainers CLI."
      repo="https://github.com/hContainers/hContainers" />
    <ProjectCard
      name="hContainersRouter"
      description="This is a router for a runner from hContainers. It (should) support a routing based on the address when using the IP address of the vm and a routing based on the domain name when assigning a (sub)domain to the vm."
      repo="https://github.com/hContainers/hContainersRouter" />
    <ProjectCard
      name="Crayon"
      description="Crayon is a go library for creating colored output in the terminal."
      repo="https://github.com/hContainers/crayon" />
  </div>
</section>
<section>
  <h1>Skills</h1>
  <SkillSection name="Infrastructure">
    <SkillCard name="Terraform" level="10" icon="terraform.png" />
    <SkillCard name="Kubernetes" level="9" icon="kubernetes.svg" />
    <SkillCard name="Docker" level="9" icon="docker.webp" />
    <SkillCard name="Ansible" level="8" icon="ansible.png" />
    <SkillCard name="Azure" level="8" icon="azure.png" />
    <SkillCard name="Hetzner Cloud" level="8" icon="hetzner.png" />
  </SkillSection>
  <SkillSection name="Programming Languages">
    <SkillCard name="Java" level="10" icon="java.png" />
    <SkillCard name="Bash" level="9" icon="bash.png" />
    <SkillCard name="Go" level="7" icon="golang.svg" />
    <SkillCard name="JavaScript" level="8" icon="javascript.png" />
    <SkillCard name="TypeScript" level="7" icon="typescript.svg" />
    <SkillCard name="PHP" level="5" icon="php.png" />
    <SkillCard name="CSS/SCSS/LESS" level="8" icon="sass.png" />
    <SkillCard name="Python" level="6" icon="python.png" />
    <SkillCard name="Haskell" level="5" icon="haskell.png" />
    <SkillCard name="C/C++" level="4" icon="c.png" />
  </SkillSection>
  <SkillSection name="Markup Languages">
    <SkillCard name="HTML" level="10" icon="html.svg" />
    <SkillCard name="Markdown" level="10" icon="markdown.svg" />
  </SkillSection>
  <SkillSection name="Frameworks & Libaries">
    <SkillCard name="Svelte/SvelteKit" level="7" icon="svelte.svg" />
    <SkillCard name="Hugo" level="8" icon="hugo.svg" />
    <SkillCard name="Spring/SpringBoot" level="9" icon="spring.svg" />
    <SkillCard name="VueJs/NuxtJs" level="5" icon="vue.svg" />
    <SkillCard name="React" level="3" icon="react.svg" />
    <SkillCard name="NodeJs" level="8" icon="nodejs.svg" />
    <SkillCard name="ExpressJs" level="7" icon="expressjs.png" />
  </SkillSection>
  <SkillSection name="CI/CD">
    <SkillCard name="GitLab CI" level="10" icon="gitlab.svg" />
    <SkillCard name="GitHub Actions" level="2" icon="githubActions.png" />
    <SkillCard name="Jenkins" level="4" icon="jenkins.svg" />
    <SkillCard name="Azure Pipelines" level="2" icon="azurePipelines.png" />
    <SkillCard name="ArgoCD" level="4" icon="argocd.png" />
  </SkillSection>
  <SkillSection name="Databases">
    <SkillCard name="SQL" level="8" />
    <SkillCard name="MySQL" level="8" icon="mysql.png" />
    <SkillCard name="MariaDB" level="8" icon="mariadb.svg" />
  </SkillSection>
  <SkillSection name="Operating Systems">
    <SkillCard name="Linux" level="9" icon="linux.png" />
    <SkillCard name="Windows" level="9" icon="windows.png" />
    <SkillCard name="MacOS" level="9" icon="macos.svg" />
  </SkillSection>
  <SkillSection name="IDEs & Tools">
    <SkillCard name="IntelliJ" level="10" icon="intellij.svg" />
    <SkillCard name="Visual Studio Code" level="10" icon="vscode.svg" />
    <SkillCard name="Postman" level="8" icon="postman.png" />
    <SkillCard name="Docker Desktop" level="9" icon="docker.webp" />
    <SkillCard name="Kubectl" level="9" icon="kubernetes.svg" />
  </SkillSection>
  <SkillSection name="Version Control">
    <SkillCard name="Git" level="10" icon="git.png" />
    <SkillCard name="GitHub" level="10" icon="github.png" />
    <SkillCard name="GitLab" level="10" icon="gitlab.svg" />
  </SkillSection>
</section>

<style>
  div {
    display: flex;
    flex-wrap: wrap;
  }

  h1 {
    font-weight: 500;
    font-size: 1.7rem;
  }
</style>
